# Generated by Django 4.0.3 on 2022-04-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailconfirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconfirmation',
            name='created',
        ),
    ]
