# Generated by Django 4.0.3 on 2022-04-05 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hotel_city_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='city',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotel',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.city'),
            preserve_default=False,
        ),
    ]
