# Generated by Django 4.0.3 on 2022-04-05 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_category_hotel_remove_city_hotel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
