# Generated by Django 4.0.3 on 2022-04-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_describe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='describe',
            new_name='description',
        ),
    ]
