# Generated by Django 4.0.3 on 2022-04-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_rename_describe_hotel_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='coords',
            new_name='coord_x',
        ),
        migrations.AddField(
            model_name='hotel',
            name='coord_y',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
